# Generated by Django 4.0.6 on 2022-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
